version: '3.8'
services:
  mlflow:
    build: .
    ports:
      - "5000:5000"
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - .:/app
    container_name: mlflow-tracking-server
